apiVersion: v1
kind: Service
metadata:
  name: flask-app1-service
spec:
  type: NodePort
  selector:
    app: flask-app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30000
