apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app1
  template:
    metadata:
      labels:
        app: flask-app1
    spec:
      containers:
      - name: flask-app1-container
        image: danish1998/flask-mongodb-app1
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "250Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "500m"
