apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app1-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
